AzureIoTHubConfig:
  IoTHubUri: iot-fsharp-hub.azure-devices.net
  IotHubD2CEndpoint: messages/events
  ConnectionString: 

DeviceConfigs:
  - Nickname: My Test Device 1
    DeviceId: Device1
    Key: 
    Status: Enabled

  - Nickname: My Test Device 2
    DeviceId: Device2
    Key: {my device key}
    Status: Enabled


NotaAzureIoTHub:
    DeviceKey: value
    IoTHubUri: iot-fsharp-hub.azure-devices.net
    DeviceId: Device1
    EndPoint: value
    ConnectionString: 
