AzureIoTHubConfig:
  IoTHubUri: iot-fsharp-hub.azure-devices.net
  IotHubD2CEndpoint: messages/events
  ConnectionString: HostName=iot-fsharp-hub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=iCQHxTcy2xQWkXNaytTzK7yxwoHlQEodvtV5nq3Qw90=

DeviceConfigs:
  - Nickname: My Test Device 1
    DeviceId: Device1
    Key: amlaRTSxbzXkDBAVejm2vxC0qjWV7nPR6MdxmEG2Py4=
    Status: Enabled

  - Nickname: My Test Device 2
    DeviceId: Device2
    Key: {my device key}
    Status: Enabled


NotaAzureIoTHub:
    DeviceKey: value
    IoTHubUri: iot-fsharp-hub.azure-devices.net
    DeviceId: Device1
    EndPoint: value
    ConnectionString: HostName=iot-fsharp-hub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=iCQHxTcy2xQWkXNaytTzK7yxwoHlQEodvtV5nq3Qw90=

