AzureIoTHubConfig:
  IoTHubUri: 
  IoTHubStorageUri:
  IoTHubStorageContainer: 
  IoTHubD2CEndpoint: messages/events
  ConnectionString: 
DeviceConfigs:
- Nickname: My Test Device
  DeviceId: DeviceId
  Key: 
  Status: Enabled
